### ISSUE TITLE
Bootstrap 4.1.3

### ISSUE THREAD

**Issue by Nilad** [djk2/django-tables2-column-shifter#13]
Hi, 

Nice to see that you up to date this tool.
Here i discover that `django-tables2-column-shifter` is not working with Bootstrap 4.1.3.

**Comment by djk2** [comment]
Thanks for info. 
I will try verify and fix problem.

**Comment by djk2** [comment]
In Bootstrap 4.1.3 documentation https://getbootstrap.com/docs/4.1/getting-started/introduction/#js
authors said that Popper.js is required. I tested with popper library and everything works fine. 
Probably you forgot about this require.

```
<script src="{% static "bootstrap4.1.3/js/popper.min.js" %}"></script>
<script src="{% static "bootstrap4.1.3/js/bootstrap.min.js" %}"></script>
```

I extended testproject and added example for B4.1.3, please see: https://github.com/djk2/django-tables2-column-shifter/tree/issue%2313/testproject.
Example added in branch: **issue#13**

**Comment by Nilad** [comment]
Yes, i forgot this require.

Everything works great.

Thanks for your reply.
