### ISSUE TITLE
how to use a custom html into system?

### ISSUE THREAD

**Issue by mzramna** [djk2/django-tables2-column-shifter#16]
there is any way to use an custom html into this? or any way to edit the existing system to acept editions,like enable an add element button

**Comment by djk2** [comment]
You can create custom template for shifter. 
Your custom template should extend my template. for example `{% extends "django_tables2_column_shifter/bootstrap4.html" %}`
If you need, you can override blocks and adjust template to your requires. 


After when you create custom template, you should override `shifter_template` attribute in your `Table` class. 

```
class YourCustomTable(ColumnShiftTableBootstrap5):
   ...
   shifter_template = "your_custom_template.html"
   ...
```

You can also extend attribut `dropdown_button_css`
