### ISSUE TITLE
Support Bootstrap 4

### ISSUE THREAD

**Issue by spapas** [djk2/django-tables2-column-shifter#18]
This is related to #17 since I presume that it won't be possible to support the django-tables2 template.

But in this case, would it be possible to somehow support bootstrap 4 (by adding maybe a new class like you do with bootstrap 2)? Right now the pagination is displayed broken in bootstrap 4 and 5.

The most important change you need to do to the `templates\django_tables2_column_shifter\bootstrap3.html` template is to change the first line to `{% extends "django_tables2/bootstrap4.html" %}`. There may be other changes but that will fix the broken pagination.

**Comment by djk2** [comment]
Please check new version 2.0 of django-tables2-column-shifter.
I also pushed new version to pypi: https://pypi.org/project/django-tables2-column-shifter/
