### ISSUE TITLE
Support bootstrap 5

### ISSUE THREAD

**Issue by spapas** [djk2/django-tables2-column-shifter#19]
This is related to issue #18 (it seems that for each version of bootstrap you'll need to have a different template) ...

In any case, for the popup to work this bootstrap 5 you need to change 

`data-toggle="dropdown"`

to 

`data-bs-toggle="dropdown"`

in the columns button:

```
                <button type="button" class="{{ table.get_dropdown_button_css }} dropdown-toggle"
                        data-bs-toggle="dropdown"
                        aria-haspopup="true"
                        aria-expanded="false"
```

**Comment by djk2** [comment]
Hi.
I just started work on support for bootstrap 5. 
I hope that new extension won't force me to break compatibility.

**Comment by djk2** [comment]
Support for bootstrap5 was added in version 2.0 of django-tables2-column-shifter.
I also pushed new version to pypi: https://pypi.org/project/django-tables2-column-shifter/
