### ISSUE TITLE
Using Issue

### ISSUE THREAD

**Issue by BrennanCode1** [djk2/django-tables2-column-shifter#23]
I followed the starting guide and for some reason i cannot get the drop down menu to work. 

Django==3.1.4
django-bootstrap4==2.3.1
django-tables2==2.3.4
django-tables2-column-shifter @ git+https://github.com/djk2/django-tables2-column-shifter@97b9516945e50b49c58dcc18128553e487fe5844

heres what im using as my requriments am i missing someting?

**Comment by djk2** [comment]
Hi. 
I will check it and I will let you know.

**Comment by djk2** [comment]
Hi. 
* Q1: What you mean when you mention about 'starting guide` - you talk about `Demo` described here: https://github.com/djk2/django-tables2-column-shifter#run-demo ?

* Q2: Why you use `django-tables2-column-shifter` installed from GitHub. Please install latest release v2.0.2 published on pypi: https://pypi.org/project/django-tables2-column-shifter/2.0.2/ 
```
pip install -U django-tables2-column-shifter`
```

For deeper analize I need more details. 
* Do you have any errors in python console?
* Do you have any errors in webbrowser js console? 
* Can you paste some screens and snipets of your code if any exist?

I will what I can do to help you.

**Comment by BrennanCode1** [comment]
Hi super sorry about being vague, updated the install to pip install, here is all the code im using if i can give you anything else let me know! My issue is whenever im clicking the visible columns drop down nothing comes down it doesnt open a menu simply nothing happens. Here is my tables.py: 
from django_tables2_column_shifter.tables import (

    ColumnShiftTableBootstrap4, # If you user bootstrap3

)
class MyModelTable(ColumnShiftTableBootstrap4):
    class Meta:
        model = Allocations


Here is my views.py def simple_list(request):
    queryset = Allocations.objects.all()
    table = MyModelTable(queryset)
    return render(request, 'WebAPP/displaythree.html', {'table': table})


Here is my displayhtml 
{%extends "WebAPP/base.html"%}

{% load render_table from django_tables2 %}
<!DOCTYPE html>
    {%block body_block%}
    <head>
        <title>List of persons</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    </head>
    <body>
        {% render_table table %}
    </body>
        {%endblock%}

here is my base.html with the code your read me instructured me to use and place
       <script src="{% static "jquery.min.js" %}"></script> {# require #}
      <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
  
      <script
          type="text/javascript"
          src="{% static "django_tables2_column_shifter/js/django_tables2_column_shifter.min.js" %}">
      </script>


placed in the body ! 

Any help you can provide would be awesome! I am recieiving no errors in the console just the drop down isnt working properly!

**Comment by djk2** [comment]
After very quick review of your code:

### Bootstrap version
I'm not sure which version of bootstrap you use.
In snip of template I see:
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
``` 
This code indicate that you use botstrap v3, but on the beginning of
this issue you wrote `django-bootstrap4==2.3.1`

### Inheritance

* If you use **bootstrap3** your table class has to inherit from `ColumnShiftTableBootstrap3` like below:
```
from django_tables2_column_shifter.tables ColumnShiftTableBootstrap3

class MyModelTable(ColumnShiftTableBootstrap3):
    class Meta:
    model = Allocations
    ...
```

* If you use **bootstrap4** your table class has to inherit from `ColumnShiftTableBootstrap4` like below:
```
from django_tables2_column_shifter.tables ColumnShiftTableBootstrap4

class MyModelTable(ColumnShiftTableBootstrap4):
    class Meta:
    model = Allocations
    ...
```

I foud small mistake in README file, and I guess that you copied code from documentation where is a small gap. 
Obviously I will fix README.rst file. 

### JS. Scripts 
If you use bootstrap3, the current js script should be enought.
But
Draw attention to fact that from version boostrap4.1
a `Popper.js` is required. 
This is a dependency for bootstrap4 JS scripts. 
Below more details: 
https://getbootstrap.com/docs/4.0/getting-started/javascript/#dependencies

Above is critical for dropdown functionality. 
Without `Popper` the part of scripts from bootstrap won't be work.
Here you can see how I implemented template for demo project using bootstrap4:
https://github.com/djk2/django-tables2-column-shifter/blob/master/testproject/testproject/templates/testproject/test_bootstrap4.1.3.html


And one small remark. 
For future, it will be much more easier read of you code,
when you try format code in GitHub issue. 
You can use triple \` char to mark a piece of code or 
just use a function `insert code <ctrl+e>` of builtin editor of GitHub.

If you have any more question, feel  free.

**Comment by djk2** [comment]
I fixed documentation, I hope that now it is more clear.
