### ISSUE TITLE
Add option to set hideable columns

### ISSUE THREAD

**Issue by Najiva** [djk2/django-tables2-column-shifter#24]
Currently all of the columns are able to be hidden away. I wanted to be able to only allow hiding some of them.

Method like self.set_hideable_columns(['A', 'B']) could do that.

**Comment by Najiva** [comment]
I have suggested the solution. How do I make a pull request?

**Comment by djk2** [comment]
Hi Najiva, will be great if you can make your own PR. 
1. First of all, if you want prepare a PR to `django-tables2-column-shifter` you must `fork` my project. 
   In right-top corner you should have button `fork` 
2.Clone it to your local system.
3. Make a new branch. `issue#24-hideable-columns`
4. Make your changes.
5. Push it back to your repo.
6. Click the Compare & pull request button.
7. Click Create pull request to open a new pull request.

In my opinion new attr must be add:`columns_allow_to_hide` or ` hideable_columns` to class `ColumnShift`. 
By default all columns should be available to hide (back compability).
This new attribute by default should be `None` or list of all columns 
Logic for new attribute and for existing one `column_default_show` should be consest - some validation should be add. 

From UI point of view this columns still will be shown but won't be active (gray)

Tests must be added.
