### ISSUE TITLE
Add possiblity to use responsive tables

### ISSUE THREAD

**Issue by mpibpc-mroose** [djk2/django-tables2-column-shifter#28]
Like in django-tables one might want to have responsive tables. This is not trivial to use as django-tables has differenz templates for responsive and non responsive.

**Comment by djk2** [comment]
Hi. 
Sorry for delay in response, unfortunately from a very long time I don't have enough time to maintain my projects on GitHub. 
If you have a some idea, please prepare some pull request for that.

**Comment by mpibpc-mroose** [comment]
Thanks a lot for your patience and support by implementing this! It was a real pleasure.
