### ISSUE TITLE
Update django-tables2-column-shifter

### ISSUE THREAD

**Issue by Nilad** [djk2/django-tables2-column-shifter#3]
Hi,

Firstly, your tool is very useful for the django community using `django-tables2`.

But, now `django-tables` can provides report with `django_tables2.export.export` options.

When i will use the latest version `django-tables2` (1.19.0), i can use the export class. But,  `django-tables2-column-shifter` doesn't work. And if i install `django-tables2-column-shifter` with your requirement setting (django-tables2 (1.6.1)), `django-tables2-column-shifter` works but i don't have the export class in `django-tables2` (this class appear in june 2017 at 1.8.0).   

Note : You version is base on the 1.6.1 version of `django-tables2` (May 2017).

So can you update your tool or help me to use it with the latest version of `django-tables2` ? Thnaks in advance.

**Comment by djk2** [comment]
Hey.
In last time I wasn't time to maintained this application.
Great hear that anyone using my code :)
Now in Poland is very cold,
so probably I will find few hours to look closer this.
Could you prepare some example code or unit test for this?
I will be gratefully.

**Comment by Nilad** [comment]
Hi,

It's great to see that you will maintain your tools with the latest version of `django-tables2`.

I am not high skilled in python to make a complete unit tests for your tool but i can test and report to you your latest build.

**Comment by djk2** [comment]
Support for django tables 2 v1.19 was added
