### ISSUE TITLE
Typo on class name

### ISSUE THREAD

**Issue by spapas** [djk2/django-tables2-column-shifter#5]
Hello, on the following line 

https://github.com/djk2/django-tables2-column-shifter/blob/a9e16c088283494e7ba7b273fcbfae75b93fcd55/django_tables2_column_shifter/templates/django_tables2_column_shifter/bootstrap3.html#L12

you have ``btn-defautl`` which probably should have been ``btn-default``. Also, there's no reason to have ``btn-xs`` two times (and also have a ``btn-sm``) there.

**Comment by djk2** [comment]
I will try fix this in this week. 
Thanks for issue.

**Comment by djk2** [comment]
Fixed. 
Changes in version 0.4.1
